version: 0.0
os: linux
files:
  - source: /app.jar
    destination: /app.jar

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 30
      runas: root
