#!/bin/bash
isExistApp = `pgrep httpd`
if [[ -n  $isExistApp ]]; then
    service httpd stop        
fi
# Stop the running Java application
# pid=$(pgrep -f 'java -jar app.jar')
# if [ -n "$pid" ]; then
#     kill -9 $pid
# fi
